# Generated by Django 5.1.1 on 2024-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('instructor_name', models.TextField(blank=True, default='', max_length=60)),
                ('course_number', models.IntegerField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
