# Generated by Django 5.1.1 on 2024-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
